# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy com:q!

version: "3.8"
networks:
  todo-network:
    driver: bridge
  
services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123
    networks:
      - todo-network
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Root@123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
volumes:
  mysql-data: